# Generated by Django 2.2.12 on 2021-02-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('num', models.TextField(null=True)),
            ],
        ),
    ]
